language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
env:
  - RAILS_VERSION=3.0.0
  - RAILS_VERSION=3.1.0
# Isn't compatible w / 3.2 yet
#  - RAILS_VERSION=3.2.0